### ISSUE TITLE
hamburger menu hides behind header text at lowest breakpoint

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-seed#13]
<img width="441" alt="screen shot 2017-07-07 at 9 50 10 pm" src="https://user-images.githubusercontent.com/895923/27981703-592ad0b0-635e-11e7-90f3-2204819ef075.png">

@ChrisPlease 
Want to take this one?

cc: @cxoltero

**Comment by thescientist13** [comment]
@ChrisPlease 
Let me know if you are interested, otherwise I will unassign and leave it up for grabs.

**Comment by ChrisPlease** [comment]
@thescientist13 So sorry, I didn't get the notification, I can definitely take this
