### ISSUE TITLE
Establish Basic Webpack Workflow

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-seed#2]
### Acceptance Criteria
Match npm scripts with webpack configuration and support basic loaders and plugins needed for spinning a simple _index.js_ with and _index.html_ for a simple hello world

webpack
- webpack.config.common - shared loaders and plugins
- webpack.config.develop - `webpack-merge` **webpack-dev-server** with common config
- webpack.config.prod - `webpack-merge` production specific loaders with common config (uglify, favicon, etc)

npm scripts
- `yarn run develop` - for local development with **webpack-dev-server**
- `yarn run build` - for production builds
- `yarn run serve` - for running a production build locally

**Comment by thisgeek** [comment]
@thescientist13 This looks like you're following the [Advanced Approach](https://webpack.js.org/guides/production/#advanced-approach) recommendations in the webpack "Production" article. Is that exactly correct, or did you intend any deviations from it?

**Comment by thescientist13** [comment]
Hey @thisgeek .

I didn't realize that it was documented as such, but yes, looks like it!
