### ISSUE TITLE
Develop a Reference App

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-seed#3]
### Acceptance Criteria
The idea is to flesh out a full reference app with a working application that can be run locally.  It should highlight specific development techniques
- forms
- AJAX
- routing
- CSS / UI Framework?  (e.g. Bootstrap)
- distinction of _views/_, components/_, services/_, etc
- _index.js_, _vendor.js_
- pull in latest version of React and all supporting libs
- update Application Layout in README.md

**Comment by thescientist13** [comment]
@ayjee / @cxoltero 
Please update the issue here with the direction proposed for the reference app implementation.

**Comment by thescientist13** [comment]
@cxoltero 
Can you please provide a summary of the scope and features you discussed with @ayjee?

**Comment by cxoltero** [comment]
Proposed app is as follows:
Simple contact list app. 
 * The user has the ability to create/edit/delete contacts.
 * All contacts data is saved locally.
 * As a step 2, user has the ability to fetch contacts from google contacts api.

<img width="666" alt="screenshot 2017-07-07 09 45 25" src="https://user-images.githubusercontent.com/7050734/27960442-4e7a002e-62f9-11e7-9a1d-8c9bb0d8acf8.png">
<img width="667" alt="screenshot 2017-07-07 09 45 57" src="https://user-images.githubusercontent.com/7050734/27960445-52473d48-62f9-11e7-9c22-74473dae9639.png">
<img width="665" alt="screenshot 2017-07-07 09 46 06" src="https://user-images.githubusercontent.com/7050734/27960447-54ae48e2-62f9-11e7-90e7-8f8d3bdaee39.png">
<img width="673" alt="screenshot 2017-07-07 09 46 17" src="https://user-images.githubusercontent.com/7050734/27960450-570f10a8-62f9-11e7-9290-4749befe4f71.png">

**Comment by thescientist13** [comment]
great stuff @cxoltero !
