### ISSUE TITLE
Unit Testing + Code Coverage

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-seed#4]
### Acceptance Criteria
Add unit testing and code coverage using Jest

**Comment by cxoltero** [comment]
are test files going to live inside a __tests__ directory? case:
```
react-seed
│
└───src
│   │  └─ file111.tsx
│   │
│   └─tests
│       │  └─ file111.spec.tsx
│       │   
```

or, are the test going to be parallel to the file. case:

are test files going to live inside a __tests__ directory? case:
```
react-seed
│
└─  src
│      └─file111.tsx
│      └─file111.spec.tsx
│      └─file222.tsx
│      └─file222.spec.tsx

```

**Comment by thescientist13** [comment]
no,  spec files will live next to the unit they are testing.  a different approach may be taken for integration and e2e tests, but that's not our intended scope here.
