### ISSUE TITLE
TypeScript / Babel configuration questions

### ISSUE THREAD

**Issue by thescientist13** [kenzanlabs/react-seed#40]
Using the current implementation, just had some questions on usage
https://github.com/kenzanlabs/react-seed/blob/master/tsconfig.json

1.  Do we need `ouputDir` if we are using webpack?
1.  Why do we have `allowJs` enabled?
1.  Why do we need to configure `include` and `exclude`.  Isn't that being handled by webpack?
1.  What is our intended transpilation strategy?  I see we are using babel and typescript loaders?  Why do we need both?  My expectation is that _.eslintrc_ + _.babelrc_  integrate with our unit test files (.jsx) and _tslint.json_ + tsconfig.json + tslint.json are for use with webpack loader.  I think there is some cleanup opportunities here.  Just want to make sure it's clear what's for what, and that our usage and intention are just as clear.
1.  We can remove the extra `coverageReporters` property in _jest.config.json_

cc: @cxoltero / @thisgeek / @ChrisPlease

**Comment by thescientist13** [comment]
This might also be a good opportunity to prune our package.json as well, or another ticket could be made if desired

**Comment by thescientist13** [comment]
@cxoltero / @thisgeek / @ChrisPlease 
Just curious on the approach presented in this repo, which looks to have TypeScript transpiled down to ES2015, and then have Babel take over.  I have never done that personally, usually opting to just have TypeScript transpile straight down to ES5.

Thoughts on these approaches?
1.  TypeScript -> ES2015 -> Babel -> ES5 (technically **babel-preset-env**)
 
or

1.  TypeScript -> ES5

Not sure which one provides a better tool chain.  It could be that using Babel gives a lot more flexibility in the end product, using some of the great presets available, which is intriguing to me.

Just want to make sure it's documented accurately for the article.

**Comment by thescientist13** [comment]
Looks like allowJS is enabled when running unit tests

**Comment by cxoltero** [comment]
I think since Typescript can compile to es5 shouldn't we just update our tests to be written in typescript and remove the babel overhead? thoughts?

**Comment by ChrisPlease** [comment]
Agree with @cxoltero on that. I think we should have TypeScript tests and skip Babel. Why clutter with multiple compilers?

**Comment by thescientist13** [comment]
I made a post in r/typescript to get some more feedback from the community.  I think it may help explain where I'm going with this.
https://www.reddit.com/r/typescript/comments/6pdcy2/transpiling_typescript_right_to_es5_or_combined/

**Comment by thescientist13** [comment]
Per @ChrisPlease here
https://github.com/kenzanlabs/react-seed/pull/50#discussion_r129354800

It turns out awesome-typescript-loader can give us the best of both worlds!
https://www.npmjs.com/package/awesome-typescript-loader#differences-between-ts-loader
> atl has first-class integration with Babel and enables caching possibilities. This can be useful for those who use Typescript with Babel. When useBabel and useCache flags are enabled, typescript's emit will be transpiled with Babel and cached. So next time if source file (+environment) has the same checksum we can totally skip typescript's and babel's transpiling. This significantly reduces build time in this scenario.

🎉
