### ISSUE TITLE
Create `npm/yarn start` script as alias of current `serve` script

### ISSUE THREAD

**Issue by mschmidt712** [kenzanlabs/react-seed#41]
The project does not currently contain a default `start` script to build and run the application. However, it contains a serve script that accomplishes this task. 

It would be great to add the default start script as an alias for the serve command.

**Comment by thescientist13** [comment]
I guess my main concern is that this is adding a task for the sake of adding a task.  The intent behind the scripts used for these projects is to follow a semantic / intuitive workflow.  Mostly, **start** just seems so ambiguous compared to **build**, **serve**, **test**, and **develop**, at least to me anyway.

Interested in what others think though.

cc: @thisgeek / @paul-barry-kenzan / @ChrisPlease / @cxoltero

**Comment by thisgeek** [comment]
I expect `start` to begin a continuously running process and `build` to have an end time.

That said, some CD/CI setups may desire complete conformity. I would say `build` is the best name for whatever a CD/CD might run, but I don't always get a choice. When I don't have a choice I'm OK with aliasing.

With aliasing in general, I advize logging something to the console that tells the user what the preferred command is.
